services:
  malzeme-teslim:
    build:
      context: /share/Container/malzeme-teslim-tutanagi
    container_name: malzeme-teslim-tutanagi
    restart: unless-stopped
    ports:
      - "8002:80"
    environment:
      - TZ=Europe/Istanbul
    labels:
      - "com.qnap.container-station.name=Malzeme Teslim Tutanagi"
